config/routes.rb
Rails.application.routes.draw do
  resources :businesses do
    resources :products, only: %i[ new create edit update destroy ]
    resource :leads, only: :show
  end

  resources :subreddits, only: %i[ index show ] do
    resources :subreddit_posts, only: %i[ index show ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "businesses#index"
end

app/models/subreddit_post.rb
class SubredditPost < ApplicationRecord
  include Embeddable
  include RedditQueries

  set_embeddable :prompt
  set_embedding_models :informer_gte

  belongs_to :subreddit, optional: true

  has_many :subreddit_post_comments, dependent: :nullify

  # Attribute to store the ranking score temporarily
  attribute :ranking_score, :float

  alias_method :comments, :subreddit_post_comments

  validates_presence_of :num_comments, :score, :ups, :upvote_ratio, :author, :author_fullname, :display_id, :domain, :name,
    :permalink, :url, :subreddit_name, :subreddit_name_prefixed, :subreddit_str_id, :title

  validates :num_comments, :score, :ups, comparison: { greater_than_or_equal_to: 0 }
  validates :name, uniqueness: true

  def prompt
    return @prompt if @prompt

    if title? && selftext?
      @prompt = <<~XML
        <title>#{title}</title>
        <description>#{selftext}</description>
      XML
      @prompt = @prompt.squish
    elsif title?
      @prompt = title
    else
      @prompt = selftext
    end
  end
end

app/controllers/subreddit_posts_controller.rb
class SubredditPostsController < ApplicationController
  before_action :set_subreddit, :set_subreddit_post, only: %i[ show ]

  def show
    @subreddit_post_comments = @subreddit_post.comments.where(depth: 0).includes(replies: { replies: :replies })
  end

  private
    def set_subreddit
      @subreddit = Subreddit.find(params[:subreddit_id])
    end

    def set_subreddit_post
      @subreddit_post = @subreddit.posts.find(params[:id])
    end
end

app/views/subreddit_posts/_subreddit_post.html.erb
<div data-controller="markdown">
  <p>Title: <strong class="font-bold text-lg"><%== subreddit_post.title %></strong></p>
  <%= link_to "Article on Reddit", subreddit_post.url, class: "underline text-blue-500" %>
  <% if subreddit_post.selftext.present? %>
    <p class="max-h-40 prose truncate" data-markdown-target="markdown"><%== subreddit_post.selftext %></p>
  <% end %>
  <p>By: <strong class="font-bold text-lg"><%= subreddit_post.author %></strong></p>
  <%= link_to "Show", subreddit_subreddit_post_path(@subreddit, subreddit_post), class: "px-2.5 py-1.5 bg-blue-500 rounded-lg font-bold text-white" %>
</div>

app/views/subreddit_posts/show.html.erb
<div>
  <div data-controller="markdown">
    <p>Title: <strong class="font-bold text-lg"><%== @subreddit_post.title %></strong></p>
    <%= link_to "Article on Reddit", @subreddit_post.url, class: "underline text-blue-500" %>
    <% if @subreddit_post.selftext.present? %>
      <p class="prose" data-markdown-target="markdown"><%== @subreddit_post.selftext %></p>
    <% end %>
    <p>By: <strong class="font-bold text-lg"><%= @subreddit_post.author %></strong></p>
  </div>

  <div data-controller="markdown" class="flex flex-col gap-2.5 mt-12">
    <%= render @subreddit_post_comments %>
  </div>
</div>