config/routes.rb
Rails.application.routes.draw do
  resources :businesses do
    resources :products, only: %i[ new create edit update destroy ]
    resource :leads, only: :show
  end

  resources :subreddits, only: %i[ index show ] do
    resources :subreddit_posts, only: %i[ index show ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "businesses#index"
end

app/models/product.rb
class Product < ApplicationRecord
  include Embeddable

  set_embeddable :prompt
  set_embedding_models :informer_gte

  belongs_to :business

  validates_presence_of :title, :description

  after_create_commit :embed_product

  def embed_product
    embed
  end

  def prompt
    return @prompt if @prompt

    @prompt = <<~XML
      <product-title>#{title}</product-title>
      <description>#{description}</description>
    XML

    @prompt = @prompt.squeeze(" ").squeeze("\n").strip
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_business
  before_action :set_product, only: %i[ edit update destroy ]

  def new
    @product = @business.products.new
  end

  def create
    @product = @business.products.new(product_params)

    render :new, status: :unprocessable_entity unless @product.save
  end

  def edit
  end

  def update
  end

  def destroy
    @product.destroy!
  end

  private
    def product_params
      params.expect(product: %i[ title description ])
    end

    def set_business
      @business = Business.find(params[:business_id])
    end

    def set_product
      @product = @business.products.find(params[:id])
    end
end

app/views/products/_product.html.erb
<div class="flex flex-col gap-1 border border-blue-500 rounded-lg p-4" id="<%= dom_id product %>">
  <p>Product Title: <%= product.title %></p>
  <p>Product Description: <%= product.description %></p>
  <%= button_to "Delete", business_product_path(@business, product), method: :delete, class: "text-white text-lg font-bold rounded-lg bg-red-500 px-2.5 py-1.5 cursor-pointer" %>
</div>

app/views/products/create.turbo_stream.erb
<%= turbo_stream.append :products do %>
  <%= render @product %>
<% end %>

<%= turbo_stream.update :new_product do %>
  <%= link_to "Add new product", new_business_product_path(@business), class: "underline", data: { turbo_frame: :new_product } %>
<% end %>

app/views/products/destroy.turbo_stream.erb
<%= turbo_stream.remove @product %>

app/views/products/new.html.erb
<%= turbo_frame_tag :new_product do %>
  <%= form_with model: @product, url: business_products_path(@business, @product), class: "flex flex-col gap-2.5" do |form| %>
    <div class="flex gap-2.5 items-center">
      <%= form.label :title, class: "font-bold" %>
      <%= form.text_field :title, class: "border rounded-lg p-2" %>
      <% if @product.errors.full_messages_for(:title).present? %>
        <p class="text-red-500"><%= @product.errors.full_messages_for(:title).to_sentence %></p>
      <% end %>
    </div>
    <div class="flex gap-2.5 items-center">
      <%= form.label :description, class: "font-bold" %>
      <%= form.text_area :description, class: "border rounded-lg p-2" %>
      <% if @product.errors.full_messages_for(:description).present? %>
        <p class="text-red-500"><%= @product.errors.full_messages_for(:description).to_sentence %></p>
      <% end %>
    </div>
    <div>
      <%= form.submit class: "px-4 py-2.5 bg-blue-500 rounded-lg text-white font-bold" %>
    </div>
  <% end %>
<% end %>