config/routes.rb
Rails.application.routes.draw do
  resources :businesses do
    resources :products, only: %i[ new create edit update destroy ]
    resource :leads, only: :show
  end

  resources :subreddits, only: %i[ index show ] do
    resources :subreddit_posts, only: %i[ index show ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "businesses#index"
end

app/models/subreddit.rb
class Subreddit < ApplicationRecord
  REDUNDANT_SUBREDDITS = JSON.parse(File.read("lib/data/redundant_subreddits.json")).freeze

  include Embeddable

  set_embeddable :embeddable_data
  set_embedding_models :informer_gte

  has_many :subreddit_posts, dependent: :nullify
  has_many :subreddit_post_comments, through: :subreddit_posts

  alias_method :posts, :subreddit_posts
  alias_method :comments, :subreddit_post_comments

  validates_presence_of *%i[subscribers display_name display_id title url description description_html name]

  validates :subscribers, comparison: { greater_than_or_equal_to: 0 }
  validates :url, uniqueness: true
  validates :display_name, exclusion: { in: REDUNDANT_SUBREDDITS }

  def embeddable_data
    return @prompt if @prompt

    @prompt = <<~XML
      <subreddit-name>#{url}</subreddit-name>
      <subreddit-title>#{title}</subreddit-title>
    XML

    @prompt = @prompt.squish
  end

  def refresh(async: false)
    if async
      RefreshSubredditJob.perform_later(id)
    else
      RefreshSubredditJob.new.perform(id)
    end
  end
end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  before_action :set_subreddit, only: %i[ show ]

  def index
    @pagy, @subreddits = pagy(Subreddit.all)
  end

  def show
    @subreddit_posts = @subreddit.posts
  end

  private
    def set_subreddit
      @subreddit = Subreddit.find(params[:id])
    end
end

app/views/subreddits/_subreddit.html.erb
<div class="rounded-lg px-4 py-2.5 border border-blue-500" data-controller="markdown">
  <%= link_to "Path to Actual Subreddit", "https://www.reddit.com/#{subreddit.url}", class: "bg-blue-500 text-white font-bold px-2.5 py-1.5" %>
  <h3 class="font-extrabold text-xl my-2.5"><%= subreddit.title %></h3>
  <p data-markdown-target="markdown" class="prose w-full"><%= subreddit.description %></p>
  <p>Total Subscribers: <%= subreddit.subscribers %></p>
  <%= link_to "Show", subreddit_path(subreddit), class: "bg-blue-500 text-white font-bold px-2.5 py-1.5 my-2.5" %>
</div>

app/views/subreddits/index.html.erb
<div class="flex flex-col gap-2.5 max-w-full">
  <%= render @subreddits %>

  <div class="mt-12">
    <%== pagy_nav(@pagy) %>
  </div>
</div>

app/views/subreddits/show.html.erb
<div>
  <div data-controller="markdown">
    <h3 class="font-black text-2xl"><%= @subreddit.title %></h3>
    <%= link_to "Visit the Subreddit", "https://www.reddit.com/#{@subreddit.url}", class: "px-2.5 py-2 bg-blue-500 text-white font-bold rounded-lg" %>
    <div class="prose" data-markdown-target="markdown">
      <%== @subreddit.description %>
    </div>
  </div>

  <div class="flex flex-col mt-20 gap-4">
    <%= render @subreddit_posts %>
  </div>
</div>